from typing import Final

# General
ROUNDING = 3

# Audio
AUDIO_EXTENSIONS = set(['.mp3', '.wav'])
SAMPLE_RATE = 22050
MONO = True

# Fingerprinting
FFT_WSIZE = 2048
FFT_OVERLAP_RATIO = 0.5
FAN_VALUE = 5
LOCAL_MAX_EPSILON = 10
AMP_MIN = 10

MIN_HASH_TIME_DELTA = 0
MAX_HASH_TIME_DELTA = 200
FINGERPRINT_REDUCTION = 20

# DB & API Configs
DATA_CONFIGS = {
    'DB_NAME': 'kishikan',
    'DIR_NAME': '../songs',
}
QUERY_BATCH_SIZE = 1000
RANKING_NUM = 6
